---
abstract: 'Pod::Weaver configuration the way DOHERTY does it'
author:
  - 'Mike Doherty <doherty@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300023, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pod-Weaver-PluginBundle-Author-DOHERTY
no_index:
  directory:
    - corpus
    - inc
    - examples
requires:
  Pod::Weaver::Config::Assembler: 0
  Pod::Weaver::Plugin::Encoding: 0
  Pod::Weaver::Section::Availability: 1.20
  Pod::Weaver::Section::BugsAndLimitations: 1.20
  Pod::Weaver::Section::SourceGitHub: 0.53
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/doherty/Pod-Weaver-PluginBundle-Author-DOHERTY/issues
  homepage: http://metacpan.org/release/Pod-Weaver-PluginBundle-Author-DOHERTY/
  repository: git://github.com/doherty/Pod-Weaver-PluginBundle-Author-DOHERTY.git
version: 0.007
